import logoUrl from "@/app/components/images/system-logo-cutout.png";

type PdfRowCell = string | number | null | undefined;

export type PdfTableReportOptions = {
  title: string;
  subtitle?: string;
  fileName?: string;
  columns: string[];
  rows: PdfRowCell[][];

  orgName?: string;
  generatedBy?: string;

  /** Defaults to landscape when there are many columns. */
  orientation?: "portrait" | "landscape";
};

let cachedLogoDataUrl: string | null = null;

async function loadImageAsDataUrl(url: string) {
  // In most browsers, fetching a same-origin Vite asset is fine. If it fails,
  // we'll just omit the logo instead of failing the export.
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`Failed to load image: ${res.status}`);
  }
  const blob = await res.blob();
  return await new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result || ""));
    reader.onerror = () => reject(new Error("Failed to read image blob"));
    reader.readAsDataURL(blob);
  });
}

async function getLogoDataUrl() {
  if (cachedLogoDataUrl) return cachedLogoDataUrl;
  cachedLogoDataUrl = await loadImageAsDataUrl(logoUrl);
  return cachedLogoDataUrl;
}

function safeFileName(input: string) {
  const trimmed = (input || "report").trim();
  const base = trimmed.length > 0 ? trimmed : "report";
  return base.replace(/[^\w\-]+/g, "_").replace(/_+/g, "_").replace(/^_+/, "");
}

function formatGeneratedAt() {
  return new Date().toLocaleString();
}

export async function exportTableReportToPdf(options: PdfTableReportOptions) {
  const orgName = options.orgName || "Murekefu Music Hub";
  const generatedAt = formatGeneratedAt();
  const title = options.title || "Report";
  const subtitle = options.subtitle || "";

  const orientation =
    options.orientation ||
    (options.columns.length > 7 ? "landscape" : "portrait");

  const [{ jsPDF }, autoTableModule] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
  ]);

  const autoTable: any = (autoTableModule as any).default || autoTableModule;

  const doc = new jsPDF({
    orientation: orientation === "landscape" ? "landscape" : "portrait",
    unit: "mm",
    format: "a4",
    compress: true,
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const marginX = 12;
  const headerHeight = subtitle ? 30 : 26;
  const footerHeight = 10;

  const brandRgb: [number, number, number] = [10, 102, 95]; // teal-ish
  const textRgb: [number, number, number] = [15, 23, 42];
  const mutedRgb: [number, number, number] = [71, 85, 105];

  let logoDataUrl: string | null = null;
  try {
    logoDataUrl = await getLogoDataUrl();
  } catch {
    // ignore
  }

  const drawHeader = (pageNumber: number) => {
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(marginX, headerHeight + 2, pageWidth - marginX, headerHeight + 2);

    // Accent bar
    doc.setFillColor(...brandRgb);
    doc.rect(marginX, 8, pageWidth - marginX * 2, 1.2, "F");

    // Logo + org name
    let logoOk = false;
    if (logoDataUrl) {
      doc.addImage(logoDataUrl, "PNG", marginX, 11, 10, 10);
      logoOk = true;
    }

    const leftTextX = logoOk ? marginX + 12 : marginX;
    doc.setTextColor(...textRgb);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text(orgName, leftTextX, 16);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...mutedRgb);
    doc.text(`Generated: ${generatedAt}`, pageWidth - marginX, 16, {
      align: "right",
    });

    doc.setTextColor(...textRgb);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(title, marginX, 24);

    if (subtitle) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(...mutedRgb);
      const maxWidth = pageWidth - marginX * 2;
      const lines = doc.splitTextToSize(subtitle, maxWidth);
      doc.text(lines, marginX, 28);
    }

    if (pageNumber > 1) {
      // Subtle page indicator on subsequent pages
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(...mutedRgb);
      doc.text(`Page ${pageNumber}`, pageWidth - marginX, headerHeight, {
        align: "right",
      });
    }
  };

  const drawFooter = (pageNumber: number, pageCount: number) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...mutedRgb);
    doc.text(
      `${orgName}${options.generatedBy ? ` | Generated by ${options.generatedBy} | ` : " | "}${generatedAt}`,
      marginX,
      pageHeight - 6,
    );
    doc.text(`Page ${pageNumber} of ${pageCount}`, pageWidth - marginX, pageHeight - 6, {
      align: "right",
    });
  };

  autoTable(doc, {
    head: [options.columns],
    body: (options.rows || []).map((row) =>
      (row || []).map((cell) => (cell === null || cell === undefined ? "" : String(cell))),
    ),
    margin: {
      top: headerHeight + 6,
      left: marginX,
      right: marginX,
      bottom: footerHeight,
    },
    styles: {
      font: "helvetica",
      fontSize: 9,
      cellPadding: 2,
      textColor: textRgb,
      overflow: "linebreak",
    },
    headStyles: {
      fillColor: brandRgb,
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    didDrawPage: (data: any) => {
      // Header (branding + title) per page
      drawHeader(data.pageNumber);
    },
  });

  const pageCount = doc.getNumberOfPages();
  for (let pageNumber = 1; pageNumber <= pageCount; pageNumber += 1) {
    doc.setPage(pageNumber);
    drawFooter(pageNumber, pageCount);
  }

  const fileName =
    options.fileName ||
    `${safeFileName(title)}_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(fileName);
}
